#!/usr/bin/env node
/**
 * Downloads the slskd daemon (Soulseek server) for this platform and writes
 * a config that makes Notify the download destination.
 *
 * Requirements: a Soulseek account (username + password).
 *   SLSKD_USERNAME / SLSKD_PASSWORD env vars are used if present, otherwise
 *   you can edit bin/slskd.yml afterwards.
 */
import { execFileSync } from 'node:child_process'
import crypto from 'node:crypto'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const BIN = path.join(ROOT, 'bin')
const DATA = path.join(ROOT, 'data')
const VERSION = '0.26.0'

// load .env (if present) so SLSKD_USERNAME/PASSWORD/API_KEY come from there
const envFile = path.join(ROOT, '.env')
if (fs.existsSync(envFile)) {
  for (const line of fs.readFileSync(envFile, 'utf8').split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    const key = trimmed.slice(0, eq).trim()
    const value = trimmed.slice(eq + 1).trim()
    if (!(key in process.env)) process.env[key] = value
  }
}

fs.mkdirSync(BIN, { recursive: true })
fs.mkdirSync(path.join(DATA, 'cache', 'original'), { recursive: true })
fs.mkdirSync(path.join(DATA, 'cache', 'incomplete'), { recursive: true })

const arch = os.arch() === 'arm64' ? 'arm64' : 'x64'
const platform = process.platform === 'darwin' ? 'osx' : process.platform === 'linux' ? 'linux' : null
if (!platform) {
  console.error('Unsupported platform. slskd supports macOS and Linux.')
  process.exit(1)
}

const zip = path.join(BIN, `slskd-${VERSION}-${platform}-${arch}.zip`)
const dest = path.join(BIN, `slskd-${platform}-${arch}`)

if (!fs.existsSync(dest)) {
  if (!fs.existsSync(zip)) {
    const url = `https://github.com/slskd/slskd/releases/download/${VERSION}/slskd-${VERSION}-${platform}-${arch}.zip`
    console.log(`Downloading slskd ${VERSION} (${platform}-${arch})…`)
    execFileSync('curl', ['-L', '-o', zip, url], { stdio: 'inherit' })
  }
  console.log('Extracting…')
  fs.mkdirSync(dest, { recursive: true })
  try {
    execFileSync('unzip', ['-o', '-q', zip, '-d', dest], { stdio: 'inherit' })
  } catch {
    // unzip isn't guaranteed on every distro — fall back to Python's stdlib
    execFileSync('python3', ['-c',
      'import sys, zipfile; zipfile.ZipFile(sys.argv[1]).extractall(sys.argv[2])',
      zip, dest], { stdio: 'inherit' })
  }
  fs.chmodSync(path.join(dest, 'slskd'), 0o755)
  fs.unlinkSync(zip)
} else {
  console.log('slskd already present.')
}

const apiKey = process.env.SLSKD_API_KEY || crypto.randomBytes(24).toString('hex')
fs.writeFileSync(path.join(BIN, 'api-key.txt'), apiKey)

const downloads = path.join(DATA, 'cache', 'original')
const incomplete = path.join(DATA, 'cache', 'incomplete')
const username = process.env.SLSKD_USERNAME || 'YOUR_SOULSEEK_USERNAME'
const password = process.env.SLSKD_PASSWORD || 'YOUR_SOULSEEK_PASSWORD'
const yml = `# generated by scripts/setup-slskd.mjs
soulseek:
  username: ${username}
  password: ${password}

directories:
  downloads: ${downloads}
  incomplete: ${incomplete}
  shares:
    - path: ${downloads}
      display_name: notify-cache

web:
  port: 5030
  authentication:
    disabled: false
    username: notify
    password: notify
    api_keys:
      notify:
        key: ${apiKey}
        cidr: 0.0.0.0/0,::/0
`
fs.writeFileSync(path.join(BIN, 'slskd.yml'), yml)
console.log(`\nslskd ready at bin/slskd-${platform}-${arch}/slskd`)
console.log(`Config:   bin/slskd.yml`)
console.log(`API key:  ${apiKey}`)
console.log(`Downloads:${downloads}`)
console.log('\nStart the daemon:')
console.log(`  bin/slskd-${platform}-${arch}/slskd --config bin/slskd.yml`)
console.log('\nThen run the backend against it:')
console.log('  SOULSEEK_MODE=slskd SLSKD_API_KEY=' + apiKey + ' node backend/src/index.js')
